name: Keep Render Alive 24/7

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Gang Web Service
        run: |
          curl -s -I https://gang.dekrew.online/health || true
